CREATE DATABASE team_project
DEFAULT CHARACTER SET utf8;


-- 유저 정보 테이블
CREATE TABLE users (
u_seq INT PRIMARY KEY AUTO_INCREMENT,
u_id VARCHAR(30) NOT NULL UNIQUE,
u_pwd VARCHAR(30) NOT NULL,
u_name varchar(30)  NOT NULL,
u_birth DATE,
u_joinDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
